### ISSUE TITLE
⭐Inquiry about open source status, collaboration, and related work

### ISSUE THREAD

**Issue by Simon1059770342** [NYU-ICL/xr-ergonomics-neck-comfort#1]
Hi Yunxiang!

May I ask if this project will be open source?
When?
Do you want to cooperate with me?

I am working on a similar task in a related field. If you have time, perhaps we can collaborate further. 

Thank you very much!

**Comment by DonQAQ** [comment]
Hi Yunxiang!
May I ask a question?
In your paper, you mentioned your prediction of the moment of inertia. How to predict the moment of inertia with a network  directly by inputting only pitch angle and angular acceleration without knowing the mass?

**Comment by yunxiangzhang** [comment]
> Hi Yunxiang!
> 
> May I ask if this project will be open source? When? Do you want to cooperate with me?
> 
> I am working on a similar task in a related field. If you have time, perhaps we can collaborate further.
> 
> Thank you very much!

Hi Simon, thanks for your interest in our work! To answer your questions:
1. Yes, both our data and code will be open-sourced, likely in late January 2024. I just didn't find the time to clean up and properly organize the repo yet...
2. For sure, I'd be happy to learn more about what you're up to and help out if I can. Would you mind sending me an email at yunxiang.zhang@nyu.edu? We can discuss further over there.

**Comment by yunxiangzhang** [comment]
> Hi Yunxiang! May I ask a question? In your paper, you mentioned your prediction of the moment of inertia. How to predict the moment of inertia with a network directly by inputting only pitch angle and angular acceleration without knowing the mass?

Hi DonQAQ, we didn't compute the moment of inertia analytically using closed-form formulas involving the mass, instead we treated it as an unknown, i.e. a trainable parameter, and optimized its value through SGD, just like the other trainable parameters in the neural network models. Also, you might want to take a look at the relationship between applied torque, moment of inertia, and angular acceleration [here](https://en.wikipedia.org/wiki/Moment_of_inertia#Definition).

**Comment by Simon1059770342** [comment]
> > Hi Yunxiang!
> > May I ask if this project will be open source? When? Do you want to cooperate with me?
> > I am working on a similar task in a related field. If you have time, perhaps we can collaborate further.
> > Thank you very much!
> 
> Hi Simon, thanks for your interest in our work! To answer your questions:
> 
> 1. Yes, both our data and code will be open-sourced, likely in late January 2024. I just didn't find the time to clean up and properly organize the repo yet...
> 2. For sure, I'd be happy to learn more about what you're up to and help out if I can. Would you mind sending me an email at [yunxiang.zhang@nyu.edu](mailto:yunxiang.zhang@nyu.edu)? We can discuss further over there.

Hi Yunxiang,

Thank you for your prompt response and for the opportunity to collaborate. I am currently conducting further research on data collection devices and once that is complete, I will get in touch with you as soon as possible. I appreciate your willingness to open source your data and code, and I look forward to potentially working together in the future.

Best,
Simon
